const dns = require('node:dns');
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/footer/Footer";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar></NavBar>
        <main>
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
